### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Trozuu** [Divine144/HLSpells#8]
Hi !

When I start the server it crashes quickly. Crash log points to the HLSpells mod. There is probably a problem with BipedModel
[crash-2021-09-09_18.09.36-fml.txt](https://github.com/Divine144/HLSpells/files/7138146/crash-2021-09-09_18.09.36-fml.txt)

**Comment by Divine144** [comment]
Can you please state the replication steps for this bug?
